# public/admin/config.yml

# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: giacovecci/mittel
  branch: main
  identity_url: https://auth.decapbridge.com/sites/6f47cec6-ee71-4b7d-a4fb-b4518e61898e
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://mittel.reiseburo.workers.dev

media_folder: "public/uploads" # Location where uploaded media files will be stored (relative to root)
public_folder: "/uploads" # The public URL path for accessing media files

collections:
  - name: "feed" # Used in routes, e.g., /admin/collections/feed
    label: "Feed Entries" # Used in the UI
    folder: "src/content/feed" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "@/layouts/BlogPost.astro" } # Assuming a layout might be needed later
      - label: "Content Blocks"
        name: "contentBlocks"
        widget: "list"
        types:
          - label: "Two Column Block"
            name: "twoColumn"
            widget: "object"
            fields:
              - { label: "Left Column (Markdown)", name: "left", widget: "markdown" }
              - { label: "Right Column (Markdown)", name: "right", widget: "markdown" }
          - label: "Full Width Image"
            name: "fullWidthImage"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
          - label: "Full Width Embed"
            name: "fullWidthEmbed"
            widget: "object"
            fields:
              - { label: "Embed Code (HTML)", name: "embedCode", widget: "text" }
      # Removed the 'body' field as content is now structured in contentBlocks
      # - { label: "Body", name: "body", widget: "markdown" } # We'll use contentBlocks instead