backend:
  name: git-gateway
  repo: giacovecci/mittel
  branch: final-mittel
  identity_url: https://auth.decapbridge.com/sites/6f47cec6-ee71-4b7d-a4fb-b4518e61898e
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://mittel.tv
publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "feed"
    label: "Feed Entries"
    folder: "src/content/feed"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - label: "Content Blocks"
        name: "contentBlocks"
        widget: "list"
        typeKey: type
        types:
          - { label: "Two Column Block", name: "twoColumn", widget: "object", fields: [ { label: "Left Column (Markdown)", name: "left", widget: "markdown", required: false }, { label: "Right Column (Markdown)", name: "right", widget: "markdown", required: false } ] }
          - { label: "Full Width Image", name: "fullWidthImage", widget: "object", fields: [ { label: "Image", name: "image", widget: "image" }, { label: "Alt Text", name: "alt", widget: "string", required: false } ] }
          - { label: "Full Width Embed", name: "fullWidthEmbed", widget: "object", fields: [ { label: "Embed Code (Raw HTML)", name: "embedCode", widget: "text" } ] }
          - { label: "Full Width Text", name: "fullWidthText", widget: "object", fields: [ { label: "Text Content", name: "text", widget: "markdown" } ] }
          - { label: "Horizontal Gallery", name: "horizontalGallery", widget: "object", fields: [ { label: "Images", name: "images", widget: "list", fields: [ { label: "Image", name: "image", widget: "image" }, { label: "Alt Text", name: "alt", widget: "string", required: false } ] } ] }

  - name: "highlights"
    label: "Highlights & Separators"
    folder: "src/content/highlights"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    summary: >
      {{title}}
      {{#if isSeparator}} (SEPARATOR) {{else}} (Order: {{order | default('N/A')}}) {{/if}}
      {{#if linkedFeedSlug}} -> {{linkedFeedSlug}} {{/if}}
    fields:
      - { label: "Title (or Separator Text)", name: "title", widget: "string" }
      - { label: "Is this a Separator?", name: "isSeparator", widget: "boolean", default: false, required: false }
      - { label: "Order", name: "order", widget: "number", value_type: "int", required: false, hint: "Used for both highlights and separators. Lower numbers appear first." }
      - { label: "Thumbnail Image (for Highlights)", name: "thumbnail", widget: "image", required: false }
      - { label: "Summary Text (for Highlights)", name: "summary", widget: "markdown", required: false }
      - { label: "Slug of Linked Feed Entry (for Highlights)", name: "linkedFeedSlug", widget: "string", required: false, hint: "Enter the exact slug of the feed entry this highlight links to (e.g., 2023-10-26-my-post-title)." }
      
  - name: "general_content"
    label: "General Content"
    files:
      - label: "Static Info (Left Column)"
        name: "static_info_content"
        file: "src/content/general_content/static_info.md"
        fields:
          - { label: "Introductory Text", name: "introText", widget: "markdown" }
          - label: "Client Logos"
            name: "clientLogos"
            widget: "list"
            required: false
            hint: "Add logos of previous clients. They will appear below the intro text."
            fields:
              - { label: "Logo Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string", hint: "Important for accessibility, e.g., 'The New York Times logo'" }
              - { label: "Link URL (Optional)", name: "link", widget: "string", required: false, hint: "Full URL if the logo should be clickable, e.g., https://www.nytimes.com" }
              - { label: "Client Name (Optional)", name: "name", widget: "string", required: false, hint: "For internal reference or future use." }
              - label: "Already Suits Dark Mode?" # ADDED
                name: "alreadySuitsDarkMode" # ADDED
                widget: "boolean" # ADDED
                default: false # ADDED
                required: false # ADDED
                hint: "Check this if the logo is already white/light and doesn't need color filtering in dark mode." # ADDED
      - label: "About Page"
        name: "about_page_content"
        file: "src/content/general_content/about_page.md"
        fields:
          - { label: "About Page Main Content", name: "aboutPageContent", widget: "markdown" }
      - label: "Contact Page"
        name: "contact_page_content"
        file: "src/content/general_content/contact_page.md"
        fields:
          - { label: "Contact Page Image", name: "contactPageImage", widget: "image", required: false }
          - { label: "Contact Page Image Alt Text", name: "contactPageImageAlt", widget: "string", required: false }
          - { label: "Contact Page Text (Markdown)", name: "contactPageText", widget: "markdown", required: false }
      - label: "Landing Page"
        name: "landing_page_content"
        file: "src/content/general_content/landing_page.md"
        fields:
          - { label: "Background Image", name: "landingPageBackgroundImage", widget: "image", required: false }
          - { label: "Background Image Alt Text", name: "landingPageBackgroundImageAlt", widget: "string", required: false, hint: "Describe the image for accessibility." }
          - { label: "Site Name (for Landing Page)", name: "landingPageSiteName", widget: "string", required: false }
          - { label: "Tagline (for Landing Page)", name: "landingPageTagline", widget: "string", required: false }
          - { label: "Location (for Landing Page)", name: "landingPageLocation", widget: "string", required: false }